version: '3.8'

services:
  mongo_db:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017" # Expose MongoDB port
    volumes:
      - mongo_data:/data/db # Persistent volume for MongoDB data
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root # Admin username
      MONGO_INITDB_ROOT_PASSWORD: root # Admin password

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081" # Expose Mongo-Express UI
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root # Match MongoDB username
      ME_CONFIG_MONGODB_ADMINPASSWORD: root # Match MongoDB password
      ME_CONFIG_MONGODB_SERVER: mongo # MongoDB service name
    restart: always

volumes:
  mongo_data: # Define a named volume for MongoDB
 